"""Build data.js, the data the page reads, from the content files:

    content/cheatsheet.json   the chuleta (sections of [what, value, ref] rows, optional table)
    content/symbols.json      the symbol sheet (sections of UNE-EN 60617 symbols)
    content/elements/         the symbol drawings (QElectroTech EN 60617 elements, converted to SVG here)

    python3 tools/build.py            # checks the content and writes data.js
    python3 tools/build.py --check    # only checks

Standard library only. The GitHub Pages workflow runs it on every push, so data.js is never committed.
"""

import datetime
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from symbols import element_file, to_svg  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
OUT = ROOT / "data.js"


def load(name):
    path = CONTENT / name
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise SystemExit(f"{path.relative_to(ROOT)}: line {e.lineno}, column {e.colno}: {e.msg}")


def check_cheatsheet(c):
    errors = []
    for i, s in enumerate(c.get("sections", []), 1):
        where = f"cheatsheet.json, section {i} ({s.get('title', 'no title')})"
        if not s.get("title"):
            errors.append(f"{where}: missing title")
        for k, row in enumerate(s.get("rows", []), 1):
            if not (isinstance(row, list) and len(row) == 3 and all(isinstance(x, str) for x in row)):
                errors.append(f"{where}, row {k}: must be [what, value, ref] (three strings; ref may be \"\")")
        t = s.get("table")
        if t:
            for k, row in enumerate(t.get("rows", []), 1):
                if len(row) != len(t.get("head", [])):
                    errors.append(f"{where}, table row {k}: {len(row)} cells but {len(t['head'])} headings")
        if not s.get("rows") and not t:
            errors.append(f"{where}: no rows and no table")
    return errors


def check_symbols(c):
    errors = []
    for i, s in enumerate(c.get("sections", []), 1):
        where = f"symbols.json, section {i} ({s.get('title', 'no title')})"
        for k, it in enumerate(s.get("items", []), 1):
            if not it.get("name") or not it.get("qet"):
                errors.append(f"{where}, symbol {k}: needs 'name' and 'qet'")
            elif not element_file(it["qet"]).is_file():
                errors.append(f"{where}, symbol {k} ({it['name']}): no element file for '{it['qet']}' "
                              f"(add it with: python3 tools/symbols.py --vendor <qelectrotech-elements checkout>)")
        if s.get("rows"):
            errors += [e.replace("cheatsheet.json", "symbols.json") for e in check_cheatsheet({"sections": [s]})]
    return errors


def main():
    cheat, syms = load("cheatsheet.json"), load("symbols.json")
    errors = check_cheatsheet(cheat) + check_symbols(syms)
    if errors:
        raise SystemExit("\n".join(errors))
    n_rows = sum(len(s.get("rows", [])) + len(s.get("table", {}).get("rows", [])) for s in cheat["sections"])
    n_syms = sum(len(s.get("items", [])) for s in syms["sections"])
    print(f"content ok: chuleta {len(cheat['sections'])} sections, {n_rows} rows · {n_syms} symbols")
    if "--check" in sys.argv:
        return
    for c in (cheat, syms):
        c.pop("_doc", None)
    for s in syms["sections"]:
        for it in s.get("items", []):
            it["svg"] = to_svg(it["qet"], star=it.get("star"), notext=it.get("notext", False))
            it.setdefault("iec", it["qet"] if re.fullmatch(r"\d\d-\d\d-\d\d", it["qet"]) else "")
    data = {"built": datetime.date.today().isoformat(), "cheatsheet": cheat, "symbols": syms}
    OUT.write_text("// Generated by tools/build.py from content/: edit those files, not this one.\n"
                   f"window.CHULETA = {json.dumps(data, ensure_ascii=False, separators=(',', ':'))};\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
